import "./globals.css";
//SHADCN CONFIG:
import { cn } from "../lib/utils"
import { Inter as FontSans } from "next/font/google"
//ICONS:
import { FaLinkedin } from "react-icons/fa6";
import { GrLineChart } from "react-icons/gr";
import { FaHeart } from "react-icons/fa6";
//COMPONENTS:
import Profile from "@/app/_components/Profile";
import { GhostIconButton } from "./_components/GhostIconButton";
import GitHub from "./_components/GitButton.jsx";
//FONTS:
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
//METADATA:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="top_navbar">
          <div>
          <GitHub />
          </div>
          <div className="top_navbar_end">
            <GhostIconButton
              Icon={<FaLinkedin />}
              iconColor="#1ecbe1"
              label="LinkedIn users"
              number={40}
            />
            <GhostIconButton
              Icon={<FaLinkedin />}
              iconColor="#11f10e"
              label="uniq. visitors"
              number={1305}
            />
            <GhostIconButton
              Icon={<FaLinkedin />}
              iconColor="#ec136b"
              label="likes and counting"
              number={678}
              underline
            />
          </div>
        </div>
        <nav>
          <div></div>
          <Profile />
        </nav>
        <div className="main">
          {children}
        </div>

      </body>
    </html>
  );
}
